extends: default

rules:
  line-length:
    max: 200
    level: warning
  truthy:
    check-keys: false
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
  comments:
    min-spaces-from-content: 1
